spring:
  datasource:
    url: jdbc:mysql://root:zlpWPZVlHRulQILDnprUwRCjNosCYxFB@autorack.proxy.rlwy.net:37190/railway
    username: root
    password: zlpWPZVlHRulQILDnprUwRCjNosCYxFB
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  server:
    port: 8080